### ISSUE TITLE
0404 Exercise 3 Scenario

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#10]
The exercise 3 from 0404-Creating device inventory reports need to be have to be redone.
Instructions are not explicit for trainees.

**Comment by BrianHinkelman** [comment]
Please note that there is a known issue with the Inventory Report lab in Module 4, and are currently working on a solution.  Please review the issue - if this is not the issue you are referring to, please provide more details.
