### ISSUE TITLE
Lab 0301 - Exercise 1

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#100]
In Lab 0301 - Exercise 1, Task 4, Step 8 the instructions don't match the current UI. 

The instructions say:

8. In the Create a profile blade, select the following options, and then select Create:

Platform: Windows 10 and later
Profile: Device restrictions

It should say:

8. In the Create a profile blade, select the following options, and then select Create:

Platform: Windows 10 and later
Profile type: Templates
Template name: Device restrictions

**Comment by BrianHinkelman** [comment]
Updated, thank you for your feedback.
