### ISSUE TITLE
Lab 0404 - Exercise 1, Task 3

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#113]
Lab: 0404
Exercise: 1
Task: 3
Step 5

"In the Contoso store, review the apps that are available. You should see Fresh Paint and Network Speed Test as available options."

This is not something that students will generally be able to see. 

According to https://docs.microsoft.com/en-us/microsoft-store/app-inventory-management-microsoft-store-for-business, it takes approximately 36 hours for apps to appear. 

Perhaps a note should be added for students indicating this, so they don't wait.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue

**Comment by BrianHinkelman** [comment]
Thank you for the suggested, added.
