### ISSUE TITLE
Lab 0202: Manage Device Enrollment into Intune

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#115]
In Lab 0202, Task 3, starting at Step 2 the options have changed. You now have Enrollment device limit restrictions and Enrollment device platform restrictions. When you create a platform restriction, you have to create the Android and iOS restrictions separately.

![image](https://user-images.githubusercontent.com/66324487/150269873-a047ae90-0324-499a-ad68-c9238671dc21.png)

**Comment by MikeVeschi** [comment]
Yep
Practice Lab: Manage Device Enrollment into Intune
Task 3: Configure Enrollment Restrictions
Step 2:  they have separated this now in the cloud with two different areas:  
"Enrollment device limit platform restrictions" and "Enrollment device platform restrictions."

We want: "Enrollment device platform restrictions," and then you can "Create restriction" from there

They have also separated out Android restrictions and iOS restrictions on their own tabs, 
so you have to do the exercise twice on the corresponding tabs to cover all those devices, 
renaming the restriction in conjunction.

**Comment by BrianHinkelman** [comment]
Thanks for reporting this, lab steps have been updated.
