### ISSUE TITLE
Supporting files for MD-101

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#12]
The supporting files for MD-101 that are stored in the MD-100 GitHub repo doesn't included the files for MD-101. For example Practice Lab - Deploying apps by using Intune.

**Comment by BrianHinkelman** [comment]
If you are referring to software files - such as the rdcman.msi file in lab 601, publically available Microsoft software is not distributed on GitHub.  It is available (or pre-installed) on lab VMs available from Authorized Lab Hosts, or you may download it from download.microsoft.com.  If there is a non-software file that you believe is missing, please let me know.

**Comment by rramoscabral** [comment]
I confirm that it is available from Authorized Lab Hosts like XmlNotepad. I assumed they would also be available on GitHub as a reference to AllFiles. Thanks for the answer :)
