### ISSUE TITLE
Lab 0202 Compliance Setups

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#126]
The steps below are no longer valid since the Compliance restrictions have been changed considerable - this section needs a rewrite

TASK3

Task 3: Configure Enrollment Restrictions
In the Microsoft Endpoint Manager admin center, select Devices.

On the Devices pane, select Enrollment restrictions. Notice that you can specify Device type restrictions and Device limit restrictions.

In the details pane, select Create restriction and then select Device type restriction.

On the Create restriction page, in the Name box enter Android and iOS Personal Device Restriction. Select Next.

On the Platform settings page, under Personally owned, select Block for the following device types:

Android Enterprise (work profile)

Android device administrator

iOS/iPadOS

**Comment by BrianHinkelman** [comment]
Thank you, steps have been updated to account for UI changes.
