### ISSUE TITLE
0601 missing display app in compay portal

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#13]
The practice lab Deploying apps by using Intune is missing the enable option for display this as a featured app in the Company Portal.

**Comment by BrianHinkelman** [comment]
This step should not be necessary to complete the lab. With the lab steps as written, the RDC app will show as available as a newest app in the company portal. Can you please provide further details on your reasons for recommending this change?

Thanks,
Brian

**Comment by rramoscabral** [comment]
It is correct, it should not be necessary to complete the lab. I usually activate the option to have the application on the main page of the company portal. It was my mistake :)

Thanks,
Ricardo Cabral
