### ISSUE TITLE
Internet Explorer is not being blocked by WIP policy

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#16]
As per the lab instructions, after setting up the WIP policy for the tenant, the Edge browser will allow access to the Sharepoint site, however IE should not be able to access the Sharepoint site, however IE is allowed.

**Comment by BrianHinkelman** [comment]
Thank you for identifying this issue.  We have identified the issue and corrected the lab (which was essentially the fact that sharepoint.com is not within the tenant AAD domain, therefore an additional boundary was needed).  A revision will be published shortly.
