### ISSUE TITLE
Device Profile lab issue...

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#17]
The chapter 5 device profile lab has an issue as the Dynamic group interface has changed in Intune:
Below is a proposed revision for the instructions:
### Task 6: Create a dynamic Azure AD device group

1.  In **LON-CL3**, in the Azure portal, scroll the page to the left and then in
    the **Azure Active Directory** blade select **Groups**.

2.  On the **Group** blade, on the details pane, select **+New group**.

3.  On the **Group** blade, provide the following values:
   a.	Group type: **Security**
   b.	Group name: **Windows Devices**
   c.	Membership type: **Dynamic Device**
   d. Under the Dynamic device members section, select the **Add dynamic query** link
   
4. On the **Dynamic membership rules** blade, select the **Property** Dropdown box and choose **deviceOSType**

5.	In the **Operator** dropdown box, choose **Contains**

6.	In the **Value** box, type **Windows**. The properties will propagate into the Rule syntax box below and look like this: device.deviceOSType -contains "Windows" 
    You may have to tab out of the Value box for the values to fill into the Rule syntax box.
    
7.	On the **Dynamic membership rules** blade, select **Save** and then **Create**.

End of proposed change.
Note: I have other updates as this class, however there's no option for creating a branch or submitting pull requests to this repo that I can find.

**Comment by BrianHinkelman** [comment]
Thanks for your suggestion.  This changeto the UI was already flagged, and was updated in the latest update.  For future updates you wish to contribute, create a Fork (not a branch), edit your forked version, and then submit a new pull request.

**Comment by swthibodeau** [comment]
Thank you Brian!

**Comment by swthibodeau** [comment]
This issue has been resolved.
