### ISSUE TITLE
Retirement of Microsoft Store for Business

### ISSUE THREAD

**Issue by jubic** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#187]
![image](https://user-images.githubusercontent.com/305868/214476947-7ae4b9bf-c526-46f8-8627-9f51894540f0.png)
As shown in the screenshot, how will this affect 0401-Deploying cloud apps using Intune?

**Comment by MSFT-rstearman** [comment]
Microsoft Store for Business retired on 3/31/23. We are currently making changes to labs and content to account for this.
