### ISSUE TITLE
Error in Lab 02, Exercise 1, Step 8.  

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#19]
At Step 8, the path it asks you to map is incorrect, it should read:

"net Use F: LON-DC1LabfilesUSMT" instead of "Net Use F: LON-DC1LabfilesInstallUSMT"

![image](https://user-images.githubusercontent.com/62155069/76649913-9079ef80-652f-11ea-8967-85f55b36b50d.png)

**Comment by BrianHinkelman** [comment]
Hi Daniel,

The current lab steps are correct. The Explorer screenshot you've provided suggests this is not the correct LON-DC1 VM for the course.  It appears to be an older VM used in a previous version of MD-101.  Please verify you have been provisioned the correct VMs provided for the current version of MD-101T00. 

Thanks,
Brian
