### ISSUE TITLE
Extensive Lab Errata

### ISSUE THREAD

**Issue by joel-rosenblum** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#20]
I have compiled an extensive lab errata for this course. There are many corrections needed for all the labs. What is the best method to get this to you? Kindest Regards, Joel

**Comment by BrianHinkelman** [comment]
Hi Joel,

First, please verify you have the correct version of the lab VMs.  Please see guidance in the updated [error_log](https://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops/blob/master/error_log.md) for information on an scenario we've been seeing regarding reported excessive issues.  If you have confirmed your VM version is correct, you can post them here. If that isn't practical, you can send me the list at my firstname.lastname@microsoft.com (my attempt to thwart the bots). 

Thanks,
Brian
