### ISSUE TITLE
AutoPilot lab Task 4

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#25]
I thought this issue was already addressed, if not, here it is.
Task 4 in the AutoPilot lab has students go into the Office Portal and then use the Devices console to set the MDM authority. 
Is this still a current process? 
I believe that since the lab setup is using an M365 E5 subscription, these steps would not be required as Intune would "be" the MDM provider.

So an updated instruction set would be:
In the browser, go to portal.azure.com
Select Intune
Select Device Enrollment
(Then instructions can pickup at step 5)

Thank you.

**Comment by BrianHinkelman** [comment]
There were some situations where the MDM may not have been set, however this Friday's update will revise these steps to use the Endpoint Manager admin center, and will indicate to set the MDM only if the orange banner indicates this is needed.
