### ISSUE TITLE
Windows updates lab issue

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#26]
The get started button does not appear on LON-CL1 in the early part of the lab, however there is red text stating that the Diagnostics level must be set to full to get preview builds.

Fix: Settings app > Privacy > Diagnostic data > change to full.

**Comment by BrianHinkelman** [comment]
Thanks for identifying this, we should be able to get this correction in this Friday's update.
