### ISSUE TITLE
password for JoinS when logging into LON-CL4

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#27]
In the Mod 4 Enrolling Devices in Intune lab. After joining CL4 to the Azure domain, we're supposed to logon as JoniS as shown below.

Select Other user, and in the Email address field type JoniS@yourtenant.onmicrosoft.com, and in the Password field, type Pa55w.rd as the password for the user and then press Enter.

Please update the password in the above instruction to: Pa55w.rd12345 as it was required that we use that password for Joni when joining the device to AAD.

**Comment by BrianHinkelman** [comment]
Thank you, this is being addressed in today's update.
