### ISSUE TITLE
Practice Lab - Create and deploy device profiles

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#28]
Looks like the section needs a major revision due to the change in the Intune profile creation process.
I like the new tabbed layout, however that makes the lab instructions confusing. 
Also, I feel the developers group will need to be created before building the profile due to the inclusion of the assignment in the overall profile creation process. If not, then we'll have to go through the initial profile creation without assigning it, then go to AD and create the group, then go back into intune and assign the profile...

**Comment by BrianHinkelman** [comment]
Thank you, this is being addressed in today's update.
