### ISSUE TITLE
Lab 0401

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#31]
Task 1 pt. 3: Would it be possible to install only the necessary RSAT tools, as installing of them took appx. 10 minutes today.
Also, the outcome of Task 4 pt. 9 is not as described. See attached screenshots.
![image](https://user-images.githubusercontent.com/57709815/82425201-7bb55d00-9a86-11ea-868c-f6961f57feeb.png)

**Comment by BrianHinkelman** [comment]
Hi Tommy,

Thanks for you're feedback. We recognize the delay with installing the RSAT and will look to include this in the next VM refresh.  In the meantime, we're reviewing this lab, and see what adjustments are needed in the steps.

**Comment by BrianHinkelman** [comment]
The results are as expected, however step 9 was not as clear as it could have been in describing what to look for.  Lab was updated in the Jul 17th update.
