### ISSUE TITLE
Lab0602-Task3

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#34]
1. On **LON-DC1**, in the Azure portal, select Intune in the navigation pane, and then on the Microsoft Intune blade, select Devices and then select All devices.

Why are you working on LON-DC1 instead LON-CL3? The server neither has the Edge Browser nor it is best practice to use a DC in the internet. Pleas change this step.

**Comment by BrianHinkelman** [comment]
Thanks for your feedback.  The changes were intended to minimize the excessive signing in and out, between admin steps and end user steps (switching to a device that was always logged in as Admin, and already in the console, would save time). We recognize this doesn't follow best practices -  when developing labs, there is frequently a trade off between time, environment capabilities, and lab goals. We're reviewing and revising steps this month, and we'll review this as well.
