### ISSUE TITLE
Lab0701, Task1 and whole Lab 07

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#35]
1. On LON-DC1, sign in as Adatum\Administrator, and then open the Microsoft Edge browser

On a server OS the Edge Browser is not present!
Also it is not best practice to use a DC to work in the internet.
Please change the lab steps to use LON-CL3 and Microsoft Edge browser! IE is not recommended for portal.azure.com!

**Comment by BrianHinkelman** [comment]
See comments in similar issue reported.
