### ISSUE TITLE
Lab 0602 Wip policy task 1 step 18

### ISSUE THREAD

**Issue by win10trainer** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#41]
yourtenant.sharepoint.com|yourtenant-my.sharepoint.com|yourtenant-files.sharepoint.com 

should be

yourtenant.sharepoint.com,yourtenant-my.sharepoint.com,yourtenant-files.sharepoint.com

**Comment by BrianHinkelman** [comment]
Can you please provide additional context on why this should be changed?  Per documentation, cloud resources are separated by pipes, using commas to designate optional proxy servers.

**Comment by win10trainer** [comment]
Hello Brian,

my students and i followed the lab on the course md-101 i taught some days ago (on learnondemand.net)  and we got an error. After changing from pipe sign to comma the input worked (but as i remember the policy did not work as expected). That was what I stated as an issue.

In the lab 0602-Configuring a WIP policy in Intune following text is displayed:

16. On the Add network boundary dialog, in the Boundary type list, select Network domains.
17. In the Name text box, type Cloud Domain name.
18. In the Value text box, type yourtenant.sharepoint.com|yourtenant-my.sharepoint.com|yourtenant-files.sharepoint.com, and then select OK

If it is a Network Domain boundary as written in the lab file the comma separator has to be used as is described in the article
https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-wip-policy-using-intune-azure

Could it be that in the lab the boundary should have been the "Cloud resource" type (which might make more sens in this context)? Then the pipe sign is the right delimiter, as i tested when i choosed the Cloud resource boundaray type
And that works even without the comma which the article says would be mandatory. Even more: If you use the comma without declaring a proxy url you get an error. So the article may be not correct in this case.

I wrote to learnondemand.net on this issue too. They modified the lab to the comma separated version, but in the meantime  i am not sure if that was right.

I hope you can decide which way was the intended way:
Instead of "Network boundary" using the "Cloud boundary" or if Network Domains boundary type is the wanted type you must  use the comma as separator instead of pipe sign.

I did some screenshots while doing these experiments and send them along with this mail.

Sincerely yours

Dr. Andreas Ihlefeld
MCT

Extract from the article:

Cloud resources
Specify the cloud resources to be treated as corporate and protected by WIP. For each cloud resource,
you may also optionally specify a proxy server from your Internal proxy servers list to route traffic for this cloud resource.
Be aware that all traffic routed through your Internal proxy servers is considered enterprise.
Separate multiple resources with the "|" delimiter. If you don’t use proxy servers, you must also include the "," delimiter just before the "|".
For example:
URL <,proxy>|URL <,proxy>

Network domains
Specify the DNS suffixes used in your environment. All traffic to the fully-qualified domains appearing in this list will be protected.
Separate multiple resources with the "," delimiter.
For example
corp.contoso.com,region.contoso.com

________________________________
Von: BrianHinkelman <notifications@github.com>
Gesendet: Dienstag, 28. Juli 2020 21:58
An: MicrosoftLearning/MD-101T00-ManagingModernDesktops <MD-101T00-ManagingModernDesktops@noreply.github.com>
Cc: andreas ihlefeld <win10trainer@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftLearning/MD-101T00-ManagingModernDesktops] Lab 0602 Wip policy task 1 step 18 (#41)


Can you please provide additional context on why this should be changed? Per documentation, cloud resources are separated by pipes, using commas to designate optional proxy servers.

**Comment by TesterTesterson1004** [comment]
Can anyone provide confirmation of this specific task actually working, and if so - which ALH and/or Tenant type was it working in and with?  I have attempted to get this task to work in several enviros using the recently updated MD101 release instructions but have thus far had zero success.

Is there any chance recent changes to Intune (i.e., moving to endpoint.microsoft.com only) and/or changes with licensing may be at work, already preventing this new instructions set from functioning?  (regarding licensing --   per this (https://docs.microsoft.com/en-us/mem/intune/apps/windows-information-protection-policy-create)  one must have an 'azure ad premium license'

**Comment by BrianHinkelman** [comment]
We are looking into the pipe vs comma issue.

Regarding licensing, every ALH should be providing each lab user with an Microsoft 365 E5 trial license, which includes Azure P2.  Please contact your ALH if you do not being provisioned a tenant with proper licensing.

Thanks,
Brian

**Comment by BrianHinkelman** [comment]
Line 16 has the error, the step should instruct to select cloud resources, not a network domain.  The pipe usage is then correct.  It is peculiar that the docs say the comma is required, when it is not. It's possible the docs need to be updated, we'll submit a request with the docs team to review.

We'll update the lab. Thank you for your efforts in bringing this to our attention!

Brian
