### ISSUE TITLE
Practice Lab - Installing the MDM Migration Analysis Tool (MMAT)

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#42]
Task 2: Step 3 

Is
    On the Github page, select the Clone or download link and select Download ZIP.

Should be
On the Github page, select Code Icon drop down and select Download ZIP

**Comment by BrianHinkelman** [comment]
MMAT lab retired in Feb 2021 update

**Comment by doifodepradeep1981** [comment]
Please help to provide MDM Migration Analysis Tool.
