### ISSUE TITLE
0203 'Enrolling Devices in Intune' - requiring MFA at several points despite all MFA settings for Tenant disabled

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#43]
I have a feeling this may apply more to a potential change or glitch within Azure, rather then being a course issue - but can anyone provide any insight as to why in '_Practice Lab - Enrolling devices in Microsoft Intune'_ LON-CL4 in Task 2, pops an MFA dialog on device join to Azure AD?  (Or, later, after successfully joining and then logging in as JoniS, MFA dialogs pop?)

- I have seen this occur fairly consistently the first time LON-CL4 joins Azure AD, despite MFA settings for device join being set to '**No'** per '_Practice Lab - Enable device management in Intune_' instructions Task 3, Step 6 '_Verify that Require Multi-Factor Auth to join devices is **set to No** and that the Maximum number of devices per user is set to 50, and then select Save_.' -- This setting has *never* been set to 'Yes':

![image](https://user-images.githubusercontent.com/49700217/99189955-bbe55780-2718-11eb-8b24-302534ad61a3.png)

- Individual Users in Azure AD have MFA set to 'Disabled' across the board (and this config has *never* been enabled at any time)

![image](https://user-images.githubusercontent.com/49700217/99189982-e6cfab80-2718-11eb-8172-f50d57fe0d44.png)

- More specifically, neither the user we are joining with (JoniS) is MFA-enabled, nor is the overall MOD Admin account:

![image](https://user-images.githubusercontent.com/49700217/99190020-18487700-2719-11eb-9a82-58e1a18f78a5.png)

![image](https://user-images.githubusercontent.com/49700217/99190043-2bf3dd80-2719-11eb-82b1-34e26cf414ff.png)

- There is only one other general MFA setting I am aware of - however the Tenant has never been configured to utilize Azure AD/Properties/Manage Security Defaults - it is, and has been, always set to 'No':

![image](https://user-images.githubusercontent.com/49700217/99189844-3bbef200-2718-11eb-8bea-66d7102d17d5.png)

Are there scenarios wherein the Azure portal/Azure AD sites force MFA regardless of individually-configured Tenant settings to *not* require it, and if so....should the Instructions add a short 'note' or 'info' block indicating as much, in case it occurs to Students taking the course?

**Comment by BrianHinkelman** [comment]
Closed per Feb 2021 update
