### ISSUE TITLE
Practice Lab - Configuring Self-service password reset (SSPR) for user accounts in Azure AD

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#44]
Task 3, Step 4 thru 17

User reports there is no longer a option to 'set up self service password reset' on the user profile page (Step 4 & 5). 

Was able to use https://aka.ms/ssprsetup to set up verification, and https://aka.ms/sspr to change the password.

**Comment by BrianHinkelman** [comment]
Closed per Feb 2021 update
