### ISSUE TITLE
0101 - Broken Download Link

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#46]
Task 3 Step 19 the download link (**https://www.microsoft.com/en-us/download/details.aspx?id=41950**) no longer works. The download is no longer available.

**Comment by DaleMcC** [comment]
It worked for my class today.

**Comment by technoloquent** [comment]
Confirmed - students and I have repeatedly gotten download not found

**Comment by BrianHinkelman** [comment]
Apparently the MOS SIA download URL has changed.  Updated URL to https://www.microsoft.com/en-us/Download/details.aspx?id=28177.

**Comment by DaleMcC** [comment]
Brian is correct: the old link worked Monday. Today the lab has been updated with the née link

DaleMcC

**Comment by directorofeducation** [comment]
The new link is to an older version of MOS SIA, but I ran through the 0101 and 0102 labs and it doesn't seem to cause any problems using the older version.

**Comment by BrianHinkelman** [comment]
Thanks for pointing that out. Not really sure what's going on - it appears two links to different versions of this are now broken, while this one remains available. We're looking into it. Please let us know if anyone has issues with the replacement link.  Will re-open this for now.
