### ISSUE TITLE
Please review all lab manuals

### ISSUE THREAD

**Issue by Siebrenkerkstra** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#6]
This version needs a compleet review of all the lab manuals.
There are to many errors to mention

e.g.  login as user debra@XXXXXXX.onmicrosoft.com (account does not exist in this stage of the course)
e.g.  there is apparently a new version of ADConnect . So the script doen't follow the interfaces

**Comment by BrianHinkelman** [comment]
Hello and thank you for your feedback.  Please check to make sure you have the latest version of the lab steps.  There was a draft version inadvertently committed to the master prior to launch, followed by a corrected version shortly after.  If you are seeing references to debra@, you may be viewing an older version.  Apologies if this is the case, releasing lab content through GitHub is a fairly new process and we are continuing to refine the process. Pardon our dust. ;)

If you believe you are reviewing the latest version, please indicate the name of the lab you are referring to.

Regarding AD Connect, a new version was published after the MD-101 launch, which prevents the domain administrator credentials from being used, and different credentials must now be used. The remaining steps still reflect the AD connect prompts in the current version.  This lab will be updated today to reflect this change.  We appreciate you taking the time to bring this to our attention. 

Thanks,
Brian
