### ISSUE TITLE
0203 Enrolling Devices into Microsoft Intune

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#77]
This issue is in the Learn on Demand environment. Lab 0203 Task 4 Step 4 is missing text. 

Learn on Demand step: "On SEA-WS3 is listed."
Correct step: "On the Devices | Overview blade, select All devices and verify that SEA-WS3 is listed."

**Comment by AustinP00** [comment]
the  MD file is already updated with this information:

![image](https://user-images.githubusercontent.com/53233868/110734234-60723480-81f5-11eb-8b57-86d138251899.png)

**Comment by directorofeducation** [comment]
Yes, I got the correct step on GitHub. I've reached out to Learn on Demand support about this as well to see if they can get it updated on their end. They have notifications that state the labs are maintained by Microsoft and to reach out directly should we locate errors. Thank you!
