### ISSUE TITLE
Lab 0801, Task 4, Step 4 (Typo)

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#79]
Replace:
Select Remove everything, and then select Local reinstall. Cloud download

With:
Select Remove everything, and then select Local reinstall. 

I know its a minor typo, but it just caught out my students so I felt it was worth raising an issue.

**Comment by AustinP00** [comment]
replacement made

**Comment by BrianHinkelman** [comment]
Thank you, this correction will be made shortly.
