### ISSUE TITLE
Practice Lab 0903 step 15 double select

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#8]
In the sentence of step 15, it has a double 'select' and can be confusing for some people.

"Select Assignments and then select Select groups to include. Choose the Enrolled Devices group and then **select Select**. Select Save."

**Comment by BrianHinkelman** [comment]
Thanks, Ricardo.  We'll get this corrected in the next update.
