### ISSUE TITLE
Lab 0303 Notepad file saved to documents doesn't sync

### ISSUE THREAD

**Issue by joannex** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#81]
...but I didn't think it should.  As this is saved in documents, my understanding is that is will NOT sync with ESR as this does not sync any data.
Please can you confirm and if so the lab be changed.

**Comment by BrianHinkelman** [comment]
You are correct, ESR does not sync docs - this was accidently left from steps related to the previous version of the lab.  Will correct.

**Comment by joannex** [comment]
Excellent, thank you.  Also Although the Edge elements do sync, of course it is not ESR doing this, but Edge itself.  Is that staying in there?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BrianHinkelman** [comment]
This correction will just this for the moment.  We realize this doesn't quite reflect ESR and Edge sync - we're working on an update for that - but it won't be in this week's update.

**Comment by davemct** [comment]
Thanks, Brian.  Every time I teach this my students all ask why the heck did they put all those items in the Start menu and move the taskbar to the right side (most people don't like that)?  Especially since, when Diego signs in to SEA-WS3, the task bar is right there at the bottom, and not on the right side where Diego put it on WS2.

I also notice a lot of sync errors in Event Viewer for both systems in DeviceManagement-Enterprise-Diagnostics-Provider.

**Comment by craigbeeremct** [comment]
I have just demo'd a successful ESR using the classroom machines. 

I'll stick the big steps here now, and spend some time this weekend on some more detailed instructions.

Create a new user, with all lowercase UPN. For example, mallory@M365x######.onmicrosoft.com.
Assign the following licenses:
- EMS E5
- Office 365 E5
- Windows 10 Ent E3

On both SEA-WS2 and SEA-WS3:

Join the machine to Azure AD as mallory. 
Restart the machine (this triggers the activation of Windows 10 using the Enterprise subscription).
Set up OneDrive for Business _(I'm not sure if this is required for ESR)_.
Enable Sync your settings.
Change wallpaper and/or colours on one machine, then log off. At the logoff time the changes will apply to the other machine.

Note that taskbar position does not apply. In my experience the colours of the taskbar are synced but not its position, or anything pinned to it. I don't know if this is deliberate (my google-fu is weak, I can't actually find a lit of exactly what settings are saved).

**Comment by ITBlandMCT** [comment]
Thanks for working this out! Here is the list of settings: [Windows Settings overview](https://docs.microsoft.com/en-us/azure/active-directory/devices/enterprise-state-roaming-windows-settings-reference#windows-settings-overview), [Windows Settings details](https://docs.microsoft.com/en-us/azure/active-directory/devices/enterprise-state-roaming-windows-settings-reference#windows-settings-details), & [What data roams?](https://docs.microsoft.com/en-us/azure/active-directory/devices/enterprise-state-roaming-faqs#what-data-roams); Taskbar position is explicitly mentioned.

**Comment by WigF1** [comment]
So, if taskbar position is explicitly mentioned and it does not move during the labs - is the documentation incorrect? Or is it like so many other labs in that we have to "hurry up and wait" ?

**Comment by craigbeeremct** [comment]
I am teaching this week and the ESR is working fine. For some of us.

I think the activation of Windows 10 has made a big difference. last time I taught this, the machines (Learn On Demand) were not activated, and I couldn't get ESR to work until I added a Win 10 license to the user.

Configuring OneDrive for Business is not required - the colour and wallpaper change happened without it (though the black background in the lab replaced the wallpaper I hit)).

I joined SEA-WS1 to Azure AD as Diego and joined SEA-WS2 as Aaron (or was it Alex - don't have the machines running right now). 
Logged on to WS1 as DiegoS@lodsaxxxxxxx.onmicrosoft.com. Went into Settings | Accounts | Sync. The option to enable it was immediately avaiable.
Logged on to WS2 as DiegoS@lodsaxxxxxxx.onmicrosoft.com. Went into Settings | Accounts | Sync. The option to enable it was disabled, and only became available after 10ish monutes, during which time I restarted WS2 and initiated Sync. Once it was available, I enabled it.

Changing start menu colours and wall paper replicated to the other machine almost instantly.

As I expected, the position of the task bar did not sync.

**Comment by BrianHinkelman** [comment]
Apologies for delay in providing updates.  We've been testing this lab with mixed results.  It does work as written, although acknowledged that it is not consistent.  Have tested suggested steps above, still seeing mixed success.  Continuing to review, and possibly revise steps.  Would appreciate if anyone has any updates.  

The taskbar move has been removed. While it should work, it's not behaving, and it's not worth additional friction it's causing.

**Comment by WigF1** [comment]
Not a single one of my students this week have had any success with start pinned apps or taskbar pinned apps working (with the lab steps performed as written). Upon checking the Event Logs, it does show two errors and a conflict.

![image](https://user-images.githubusercontent.com/12164329/135348313-875e5833-8504-42ac-8921-f4798d921f76.png)

![image](https://user-images.githubusercontent.com/12164329/135348557-30daa5ad-4a07-4b87-944c-58583c1f0fc1.png)

The associated scheduled tasks seem to run, but it's not syncing what it is 'supposed to'. Changing  the primary mouse button is near instantaneous. You can demo that with Diego logged into both machines no worries. However, on the same mouse settings dialog, the other settings down roam. 

My honest feeling is that this just adds to the list of things that don't work 'as intended' or are 'inconsistent' and possibly needs removing.

**Comment by WigF1** [comment]
One other thing re the ESR lab, according to this URL : https://docs.microsoft.com/en-us/azure/active-directory/devices/enterprise-state-roaming-windows-settings-reference, the start screen layout does not sync. 

![image](https://user-images.githubusercontent.com/12164329/135536056-fb4f5e11-0caf-4119-b977-7314f0e9108d.png)

The lab should be changed to avoid pinning apps to the taskbar and avoid pinning them to the start screen. We should focus on what does sync.

**Comment by WigF1** [comment]
16 people and no start menu pinning or taskbar pinning sync'd. This really needs to be removed from the lab steps.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by BrianHinkelman** [comment]
Updated steps to change background and mouse.

**Comment by craigbeeremct** [comment]
I know this issue is closed, but I'd like to add a suggestion.

Add instructions to remove BackInfo.exe from the startup menu. That way, when we change the wallpaper, we actually see the wallpaper change and stay changed.

Run Explorer. Navigate to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup. Delete the Backinfo shortcut.
