### ISSUE TITLE
0401 - Deploying cloud apps using Intune

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#82]
Lab 0401 - Deploying cloud apps using Intune
Task 1
Step 10

The Appstore URL points to the Canadian store: https://www.microsoft.com/en-ca/p/microsoft-remote-desktop/9wzdncrfj3ps it should point to the US store: https://www.microsoft.com/en-us/p/microsoft-remote-desktop/9wzdncrfj3ps

**Comment by AustinP00** [comment]
replacement made for temporary fix

**Comment by BrianHinkelman** [comment]
Thanks, will remove region.
