### ISSUE TITLE
Flow of content

### ISSUE THREAD

**Issue by win10trainer** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#88]
I think it would make sense in module 4  to first describe the application deployment and at last the mam and app protection. This would allow to first do the application deployment lab after teaching the the first part and then after teaching the mam part do the app protection lab. I do it myself but would be nice to have the powerpoints and module lessons reordert in the course material. Just an idea.

**Comment by BrianHinkelman** [comment]
Thanks, we will take this into consideration for future updates.
