### ISSUE TITLE
Lab 0301 - Rule syntax is incorrect

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#89]
# Lab 0301
### Task 6

In Step 5, the rule won't work unless it is enclosed in parentheses. (Oddly, the verification will work, but the membership won't be populated.)
Corrected:
```powershell
(device.deviceOSType -contains "Windows")
```

**Comment by BrianHinkelman** [comment]
Corrected, thank you.
