### ISSUE TITLE
Lab 06, Practice Lab: Configure and Deploy Windows Information Protection Policies by using Intune

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#91]
_Task 6, step 4: Take note of the briefcase icon at the right side of the address bar. Select the icon and verify that this website is managed by the tenant._

The briefcase icon is on the LEFT side.  When selected, it does not display any information about the management of the website, except to show Secure Content.

If there is supposed to be a briefcase icon to the right, it is not displaying.

**Comment by ITBlandMCT** [comment]
It is working in my lab right now.
![Screenshot 2021-04-16](https://user-images.githubusercontent.com/20519564/115073999-b73af000-9ebe-11eb-95fc-829ca311c187.png)

**Comment by davemct** [comment]
Thanks.  All is configured correct.  But still no briefcase.

This worked once for me (Saturday) and I was going to pull this issue, but as I taught it this week (yesterday), once again one of my students and I could not get the policy to set on WS1.

After the class is over I'll go back and do the entire lab again.

**Comment by BrianHinkelman** [comment]
Have been able to repro the briefcase not appearing only on one occasion, but the policies were still in effect.  Closing this issue, please comment if still a concern.

**Comment by pascalcanza** [comment]
Have been able to repro the briefcase not appearing too...
