### ISSUE TITLE
Lab 0404: Deploying Apps using Microsoft Store for Business

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#92]
Exercise 1
Task 2
Step 4

The Translator app is no longer available in the Made by Microsoft section.

**Comment by davemct** [comment]
I had the students pick the Reader app (although it is no longer usable, as Edge can read PDFs, it will allow you to install).

**Comment by BrianHinkelman** [comment]
Corrected, thanks.
