### ISSUE TITLE
Lab 0404: Deploy Apps using Microsoft Store for Business

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#93]
Exercise 2
Task 1
Step 1

This lab does not inform the student to switch back to SEA-CL1 where the Microsoft Endpoint admin center is still open. Requesting that step be added as Step 1.

**Comment by davemct** [comment]
Exercise 1, task 4, step 4.  Contoso does not appear, even when you go to More (...)

**Comment by BrianHinkelman** [comment]
Corrected, thank you.
