### ISSUE TITLE
Translator App no longer available in the Microsoft Store

### ISSUE THREAD

**Issue by Bobkr01** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#95]
As of April 8, 2021, the Microsoft Translator App is no longer available in the Microsoft Store (https://www.microsoft.com/en-us/translator/blog/2021/03/24/microsoft-translator-app-for-windows-desktop-will-be-retired-soon/).

This will affect _Exercise 1: Add a Microsoft Store App to Intune, Task 2: Purchasing and Adding apps to the Private Store, Steps 4 thru 9_.

I had students choose another Applications for now; **Windows Notepad**

**Comment by BrianHinkelman** [comment]
Thank you, we will update in today's update.
