### ISSUE TITLE
Labs should not depend on each other.

### ISSUE THREAD

**Issue by dddentais** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#96]
Having the entire set of labs dependent on each other is a very bad idea.  If a student has problems late in the lab work and resets his environment he has to start all over again from the beginning.  Can you imagine the hostility a student will feel being told on Thursday that he has to start again by redoing all of the labs starting from Monday?

Given the frequent changes to the lab environment and the Azure interface this chapter by chapter lab dependency invites problems.  Students get confused or make bad mistakes and sometime it so muddles the environment that a reset is the best choice rather than spending time we do not have in class to fix problems whose origin and cause may not be easily determinable.  If a student's lab goes haywire then he is either struggling to redo all the previous lab work to get caught up or he is effectively no longer doing labs for the remainder of the course; both of these are unacceptable outcomes for a student.

Also, sometimes students (and myself) want to redo a lab to test other ways of doing things or to see again what was done in order to gain a deeper insight.  With the labs tied together like this and thus the lab environment being very brittle this sort of learning and experimentation is not possible.

Also, how can we create custom courses with specific chapters with the lab environment set up this way?

The labs for each chapter should be completely independent of each other.  MS Education tried tying labs together like this back with the old NT courses in the 1990s and stopped it.  Why are we doing this now?

**Comment by billfitzgerald-415** [comment]
I can totally concur with this.  As an instructor, I HATE having a lab build on a previous lab.  And the lab company we use - Go Deploy - will delete a lab if not accessed in 4 days.  So that means even if you are on vacation, the lab must be accessed, or it is lost.  Not a smart way to run these labs.  And if you want to re-do a particular lab, forget about it.  I taught the Server 2016 courses, 70-740, 70-741, and 70-742, we NEVER had these problems.  I would STRONGLY suggest revamping the labs so if you DO have an issue, you can restart the labs with no issues.

**Comment by BrianHinkelman** [comment]
This conversation really is best suited for the MCT forums, as GitHub is for reporting and suggesting fixes to specific issues.

However, as there appears to be a perception that WWL is unaware or disinterested in the challenges with dependent labs, I'll try to offer some perspective. We generally don't like dependent labs as well. They are harder to develop and harder to test - it's really is no picnic for us either. This doesn't represent a shift to dependent labs - you'll note the MD-100 labs are independent. But the tenant creates challenges here with regard to the MDA topics. For example, we can't snapshot a tenant configuration, nor can we snapshot devices already enrolled or pre-stage scenarios like AD sync. We also have to find balance when considering the number of VMs needed. 

The reality is, many of the lab scenarios in later labs, require configuration, which are the very steps being covered in earlier labs. You may recall, the MD-101 labs were less dependent a couple years ago. This resulted in students having to perform repetitive, mundane steps frequently in the labs such as unenrolling and re-enrolling devices. This resulted in receiving considerable negative feedback, one of the primary reasons why we changed.  We do get it. We've been there when a lab goes south - as an instructor and as a student.  But there is also a need to make trade-offs between what we want to accomplish and the challenges that on-demand lab environments and tenants present. We frequently explore solutions (scripting, for example) - currently, we haven't identified a solution that we feel is reliable enough to implement.

If you have suggestions to make specific labs less dependent, we can certainly review for future updates. Forking is available for customization. It doesn't seem like a student would need to repeat every lab step to catch-up late in the week, but the challenge is understandable. I encourage reaching out to the MCT community for suggestions. For challenges related to an ALH - recommend bringing your concerns directly to the ALH.
